v2.0 ios
Picovoice/leopard pull request #301
Opened 2023-11-22 20:19 UTC by ksyeo1010

2023-11-23 00:44 UTC, laves requested changes

2023-11-23 00:44 UTC, laves commented on binding/ios/Leopard.swift
> +    ///   - speakerTag: he speaker tag is `-1` if diarization is not enabled during initialization;
```suggestion
    ///   - speakerTag: The speaker tag is `-1` if diarization is not enabled during initialization;
```

2023-11-23 00:44 UTC, laves commented on binding/ios/Leopard.swift
> +            throw pvStatusToLeopardError(status, "Leopard process failed", messageStack)
```suggestion
            throw pvStatusToLeopardError(status, "Leopard process file failed", messageStack)
```

2023-11-23 00:44 UTC, laves commented on binding/ios/LeopardAppTest/LeopardAppTestUITests/LeopardAppTestUITests.swift
> +        for i in 0..<words.count {
assert len of words == expectedWords

2023-11-23 01:12 UTC, laves requested changes

2023-11-23 01:12 UTC, laves commented on binding/ios/Leopard.swift
> +                enableDiarization,
you're missing the actual call to `pv_set_sdk` - double check that this is present in all your SDKs. If it's missing in one, it'll mess up our stats and we'll have to do a rerelease

2023-11-23 22:52 UTC, ksyeo1010 commented
react native relies on this PR, this PR relies on RN pr.

2023-11-24 00:23 UTC, laves approved these changes

2023-11-24 00:23 UTC, merged