Ios update rn flutter
Picovoice/leopard pull request #408
Opened 2024-12-24 01:32 UTC by albho

2024-12-24 02:01 UTC, albho commented
Will need to release before merge

2024-12-31 17:14 UTC, laves requested changes

2024-12-31 17:14 UTC, laves commented on demo/flutter/ios/Runner.xcodeproj/project.pbxproj
> +				IPHONEOS_DEPLOYMENT_TARGET = 12.0;
I believe our ios binding is iOS 13.0 minimum - we should change the deployment targets to 13.0 where applicable

2025-01-03 17:58 UTC, laves approved these changes

2025-01-03 17:58 UTC, laves commented
seems like you have a pipeline failure - fix that first and then you can do a release

2025-01-03 20:27 UTC, albho commented
@laves `demos build-ios` failures are due to `react-native` trying to get `boost` from `jfrog`, which is currently broken. Followed [this GitHub issue](https://github.com/boostorg/boost/issues/996) to fix this by using `patch-package` to get `boost` from `sourceforge` instead of `jfrog`.

2025-01-03 21:37 UTC, laves commented
yeesh, what a mess. Okay, well you can go ahead and release

2025-01-03 21:37 UTC, laves approved these changes

2025-01-06 18:26 UTC, merged