leopard microservice with grpc
Picovoice/leopard pull request #68
Opened 2022-04-21 22:33 UTC by mrrostam

2022-04-22 00:10 UTC, ksyeo1010 approved these changes

2022-04-22 00:10 UTC, ksyeo1010 commented on demo/go-grpc/readme.md
> +Replace `${ACCESS_KEY}` with yours obtained from Picovoice Console and `${AUDIO_PATH}` with a path to an audio file you
lets move ${AUDIO_PATH} stuff to client

2022-04-22 00:10 UTC, ksyeo1010 commented on demo/go-grpc/readme.md
> +--audio_file "${AUDIO_PATH}"
either put this as -input_audio or change client.go to use audio_file

2022-04-22 00:11 UTC, ksyeo1010 commented
I think we should use 4 spaces instead of tabs

2022-04-26 01:00 UTC, laves requested changes
Code looks good!

2022-04-26 01:31 UTC, merged